all:
    resource: "@AllBundle/Controller/"
    type:     annotation
    prefix:   /

index:
    path: /
    defaults: { _controller: AllBundle:User:index}

app:
    resource: '@AppBundle/Controller/'
    type: annotation

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:contact }