all:
    resource: "@AllBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /
    defaults: { _controller: AllBundle:User:login}

app:
    resource: '@AppBundle/Controller/'
    type: annotation

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:contact }

news:
    path:     /news
    defaults: { _controller: AllBundle:News:news }