all:
    resource: "@AllBundle/Controller/"
    type:     annotation
    prefix:   /

connected:
    path: /news
    defaults: { _controller: AllBundle:User:index}

info:
    path: /info
    defaults: { _controller: AllBundle:User:info}

app:
    resource: '@AppBundle/Controller/'
    type: annotation

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:contact }

news:
    path:     /news
    defaults: { _controller: AllBundle:News:news }

livret:
    path:     /livret
    defaults: { _controller: AllBundle:Livret:livret }