AppBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        phone:
            type: string
            length: 255
        address:
            type: string
            length: 255
        email:
            type: string
            length: 255
        birthday:
            type: string
            length: 255
    lifecycleCallbacks: {  }
